### PR TITLE
Tests: disable global git configuration

### PR DESCRIPTION
**Pull request by Khady**
I am under the impression that the tests can be affected by user and global git configuration, in addition to things like git version. This is an attempt to reduce the problem as much as possible.

### CODE REVIEW

**Comment by hhugo** [comment]
Thanks. Are the tests passing for you with my 2 new commits ?

**Comment by Khady** [comment]
using a recent git reduced the noise, but the commit hashes still are different

```diff
File "test/resolve2.ml", line 1, characters 0-0:
diff --git a/_build/default/test/resolve2.ml b/_build/default/test/resolve2.ml.corrected
index e41316f..0348867 100644
--- a/_build/default/test/resolve2.ml
+++ b/_build/default/test/resolve2.ml.corrected
@@ -43,12 +43,12 @@ type t =
         {|
         Auto-merging b.ml
         CONFLICT (content): Merge conflict in b.ml
-        error: could not apply b60ee5f... second commit (fork)
+        error: could not apply 1230bfa... second commit (fork)
         hint: Resolve all conflicts manually, mark them as resolved with
         hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
         hint: You can instead skip this commit: run "git rebase --skip".
         hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
-        Could not apply b60ee5f... second commit (fork)
+        Could not apply 1230bfa... second commit (fork)
         Exit with 1 |}];
       print_status ();
       [%expect
@@ -67,7 +67,7 @@ type t =
             b : string;
             c : float;
           }
-        >>>>>>> b60ee5f (second commit (fork)):a.ml |}];
+        >>>>>>> 1230bfa (second commit (fork)):a.ml |}];
       resolve ();
       [%expect {| Resolved 1/1 b.ml |}];
       print_status ();
@@ -83,5 +83,5 @@ type t =
       system "git rebase --continue";
       [%expect
         {|
-        [detached HEAD e87f8c3] second commit (fork)
+        [detached HEAD 2ad93fa] second commit (fork)
          1 file changed, 6 insertions(+), 6 deletions(-) |}])
```

**Comment by hhugo** [comment]
Same issue with the CI. See https://github.com/hhugo/merge-fmt/pull/6. Yet some other commit hash

**Comment by hhugo** [comment]
I figured it out. `GIT_AUTHOR_DATE` was missing tz offset. Waiting for ci #6

**Comment by hhugo** [comment]
This has been merged as part of #6.

**Comment by Khady** [comment]
thanks!

**Pull request closed without merging**
